# Generated by Django 2.2 on 2022-08-21 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complain', '0011_auto_20220821_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplainPriorityModel',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('complain_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='complain.ComplainModel')),
                ('complain_priority', models.CharField(max_length=512)),
                ('complain_status', models.CharField(max_length=2048)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
