# Generated by Django 2.2 on 2022-08-21 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplainModel',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('complain_id', models.AutoField(primary_key=True, serialize=False)),
                ('complain_title', models.CharField(max_length=512)),
                ('complain_desc', models.CharField(max_length=2048)),
                ('location_house_number', models.CharField(max_length=128)),
                ('location_area', models.CharField(max_length=128)),
                ('location_city', models.CharField(max_length=128)),
                ('location_state', models.CharField(max_length=128)),
                ('location_postal_code', models.CharField(max_length=128)),
                ('access', models.CharField(choices=[('pvt', 'Private'), ('public', 'Public')], default='public', max_length=128)),
                ('affected_people_count', models.IntegerField()),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
