# Generated by Django 2.2 on 2022-08-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0002_auto_20220821_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainmodel',
            name='affected_people_count',
            field=models.IntegerField(null=True),
        ),
    ]
