# Generated by Django 2.2 on 2022-08-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0004_auto_20220821_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainmodel',
            name='affected_people_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
