# Generated by Django 2.2 on 2022-08-15 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_auto_20220816_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccountmodel',
            old_name='id',
            new_name='user',
        ),
    ]
